version: 2

project_name: sonosh

changelog:
  disable: true

builds:
  - id: sonosh
    main: ./cmd/sonosh
    binary: sonosh
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64
      - windows_arm64

universal_binaries:
  - id: sonosh
    ids:
      - sonos
    name_template: sonosh
    replace: false

archives:
  - ids:
      - sonos
    formats:
      - tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if and (eq .Os "darwin") (eq .Arch "all") }}macos-universal{{ else }}{{ .Os }}_{{ .Arch }}{{ end }}'
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt
